git rm     Aorta/ofCaseGen/Method_4/README.md
        git rm     Aorta/ofCaseGen/Method_4/__init__.py
        git rm     Aorta/ofCaseGen/Method_4/config.py
        git rm     Aorta/ofCaseGen/Method_4/data/convex_hull_creator.py
        git rm     Aorta/ofCaseGen/Method_4/data/correlation_analysis.py
        git rm     Aorta/ofCaseGen/Method_4/data/data_bound_with_morphed_data.py
        git rm     Aorta/ofCaseGen/Method_4/data/data_bound_with_morphed_data_manual.py
        git rm     Aorta/ofCaseGen/Method_4/data/data_bound_with_patient_data.py
        git rm     Aorta/ofCaseGen/Method_4/data/data_bound_with_patient_data_manual.py
        git rm     Aorta/ofCaseGen/Method_4/data/distribution.py
        git rm     Aorta/ofCaseGen/Method_4/data/distribution_modified.py
        git rm     Aorta/ofCaseGen/Method_4/data/distribution_with_patient_data.py
        git rm     Aorta/ofCaseGen/Method_4/data/distribution_with_patient_data_modified.py
        git rm     Aorta/ofCaseGen/Method_4/data/fit_distributions.py
        git rm     Aorta/ofCaseGen/Method_4/data/geom_vs_age_box_plot.py
        git rm     Aorta/ofCaseGen/Method_4/data/input/U/U_bottom.txt
        git rm     Aorta/ofCaseGen/Method_4/data/input/U/U_parabolicTimeVaryingInlet
        git rm     Aorta/ofCaseGen/Method_4/data/input/U/U_pulsatileSwirl
        git rm     Aorta/ofCaseGen/Method_4/data/input/U/U_top.txt
        git rm     Aorta/ofCaseGen/Method_4/data/input/U/velocity_time.csv
        git rm     Aorta/ofCaseGen/Method_4/data/input/U/velocity_time_old.csv
        git rm     Aorta/ofCaseGen/Method_4/data/input/aaa_data.xlsx
        git rm     Aorta/ofCaseGen/Method_4/data/input/of_base_case/.DS_Store
        git rm     Aorta/ofCaseGen/Method_4/data/input/of_base_case/0/.DS_Store
        git rm     Aorta/ofCaseGen/Method_4/data/input/of_base_case/0/U
        git rm     Aorta/ofCaseGen/Method_4/data/input/of_base_case/0/p
        git rm     Aorta/ofCaseGen/Method_4/data/input/of_base_case/aorta_jobscript
        git rm     Aorta/ofCaseGen/Method_4/data/input/of_base_case/collectAndZipPostProcessing.sh
        git rm     Aorta/ofCaseGen/Method_4/data/input/of_base_case/constant/.DS_Store
        git rm     Aorta/ofCaseGen/Method_4/data/input/of_base_case/constant/transportProperties
        git rm     Aorta/ofCaseGen/Method_4/data/input/of_base_case/constant/triSurface/.DS_Store
        git rm     Aorta/ofCaseGen/Method_4/data/input/of_base_case/constant/turbulenceProperties
        git rm     Aorta/ofCaseGen/Method_4/data/input/of_base_case/extract-multiple-wss-percentiles.sh
        git rm     Aorta/ofCaseGen/Method_4/data/input/of_base_case/foam.foam
        git rm     Aorta/ofCaseGen/Method_4/data/input/of_base_case/paraGeomWssStream.py
        git rm     Aorta/ofCaseGen/Method_4/data/input/of_base_case/paraGeomWssStream.sh
        git rm     Aorta/ofCaseGen/Method_4/data/input/of_base_case/paraOsi.py
        git rm     Aorta/ofCaseGen/Method_4/data/input/of_base_case/paraOsi.sh
        git rm     Aorta/ofCaseGen/Method_4/data/input/of_base_case/paraOsiCyclePlot.py
        git rm     Aorta/ofCaseGen/Method_4/data/input/of_base_case/paraOsiCyclePlot.sh
        git rm     Aorta/ofCaseGen/Method_4/data/input/of_base_case/paraTawss.py
        git rm     Aorta/ofCaseGen/Method_4/data/input/of_base_case/paraTawss.sh
        git rm     Aorta/ofCaseGen/Method_4/data/input/of_base_case/paraTawssCyclePlot.py
        git rm     Aorta/ofCaseGen/Method_4/data/input/of_base_case/paraTawssCyclePlot.sh
        git rm     Aorta/ofCaseGen/Method_4/data/input/of_base_case/paraWssTimePlot.py
        git rm     Aorta/ofCaseGen/Method_4/data/input/of_base_case/paraWssTimePlot.sh
        git rm     Aorta/ofCaseGen/Method_4/data/input/of_base_case/postprocess.sh
        git rm     Aorta/ofCaseGen/Method_4/data/input/of_base_case/system/.DS_Store
        git rm     Aorta/ofCaseGen/Method_4/data/input/of_base_case/system/blockMeshDict
        git rm     Aorta/ofCaseGen/Method_4/data/input/of_base_case/system/controlDict
        git rm     Aorta/ofCaseGen/Method_4/data/input/of_base_case/system/decomposeParDict
        git rm     Aorta/ofCaseGen/Method_4/data/input/of_base_case/system/fvSchemes
        git rm     Aorta/ofCaseGen/Method_4/data/input/of_base_case/system/fvSolution
        git rm     Aorta/ofCaseGen/Method_4/data/input/of_base_case/system/snappyHexMeshDict
        git rm     Aorta/ofCaseGen/Method_4/data/input/of_base_case/system/surfaceFeaturesDict
        git rm     Aorta/ofCaseGen/Method_4/data/input/of_base_case/system/wallShearStress
        git rm     Aorta/ofCaseGen/Method_4/data/input/shm/shm_bottom.txt
        git rm     Aorta/ofCaseGen/Method_4/data/input/shm/shm_top.txt
        git rm     Aorta/ofCaseGen/Method_4/data/output/files/U
        git rm     Aorta/ofCaseGen/Method_4/data/output/files/blockMeshDict
        git rm     Aorta/ofCaseGen/Method_4/data/output/files/corrected_velocity_time.csv
        git rm     Aorta/ofCaseGen/Method_4/data/output/files/snappyHexMeshDict
        git rm     Aorta/ofCaseGen/Method_4/data/processed/convex_hull_metadata.json
        git rm     Aorta/ofCaseGen/Method_4/data/processed/fitted_distributions.json
        git rm     Aorta/ofCaseGen/Method_4/data/zip_it.py
        git rm     Aorta/ofCaseGen/Method_4/main.py
        git rm     Aorta/ofCaseGen/Method_4/src/.DS_Store
        git rm     Aorta/ofCaseGen/Method_4/src/__init__.py
        git rm     Aorta/ofCaseGen/Method_4/src/ofCaseGen/.DS_Store
        git rm     Aorta/ofCaseGen/Method_4/src/ofCaseGen/clean_and_repeat_cardiac_cycle.py
        git rm     Aorta/ofCaseGen/Method_4/src/ofCaseGen/compute_normals.py
        git rm     Aorta/ofCaseGen/Method_4/src/ofCaseGen/convert_velocity_components.py
        git rm     Aorta/ofCaseGen/Method_4/src/ofCaseGen/correct_normal.py
        git rm     Aorta/ofCaseGen/Method_4/src/ofCaseGen/create_block_mesh_dict.py
        git rm     Aorta/ofCaseGen/Method_4/src/ofCaseGen/create_openfoam_case.py
        git rm     Aorta/ofCaseGen/Method_4/src/ofCaseGen/create_snappy_hex_mesh_dict.py
        git rm     Aorta/ofCaseGen/Method_4/src/ofCaseGen/find_point_inside_stl.py
        git rm     Aorta/ofCaseGen/Method_4/src/ofCaseGen/generate_u_file.py
        git rm     Aorta/ofCaseGen/Method_4/src/ofCaseGen/read_stl_ascii.py
        git rm     Aorta/ofCaseGen/Method_4/src/ofCaseGen/read_stl_binary.py
        git rm     Aorta/ofCaseGen/Method_4/src/ofCaseGen/read_stl_file.py
        git rm     Aorta/ofCaseGen/Method_4/src/vesselGen/.DS_Store
        git rm     Aorta/ofCaseGen/Method_4/src/vesselGen/__init__.py
        git rm     Aorta/ofCaseGen/Method_4/src/vesselGen/compute_equidistant_points_and_normals.py
        git rm     Aorta/ofCaseGen/Method_4/src/vesselGen/convert_points_for_cylinder.py
        git rm     Aorta/ofCaseGen/Method_4/src/vesselGen/create_asymmetric_aneurysm.py
        git rm     Aorta/ofCaseGen/Method_4/src/vesselGen/cylinder_triangulation.py
        git rm     Aorta/ofCaseGen/Method_4/src/vesselGen/geom_info/anatomical_points.txt
        git rm     Aorta/ofCaseGen/Method_4/src/vesselGen/geom_info/centerline_points.txt
        git rm     Aorta/ofCaseGen/Method_4/src/vesselGen/geom_info/cross_section_normals.txt
        git rm     Aorta/ofCaseGen/Method_4/src/vesselGen/geom_info/cross_section_points.txt
        git rm     Aorta/ofCaseGen/Method_4/src/vesselGen/geom_info/geometry_visualization.png
        git rm     Aorta/ofCaseGen/Method_4/src/vesselGen/geom_info_main.py
        git rm     Aorta/ofCaseGen/Method_4/src/vesselGen/geometry_designer.py
        git rm     Aorta/ofCaseGen/Method_4/src/vesselGen/lhsdesign.py
        git rm     Aorta/ofCaseGen/Method_4/src/vesselGen/perturb_vertices.py
        git rm     Aorta/ofCaseGen/Method_4/src/vesselGen/remove_intermediate_faces.py
        git rm     Aorta/ofCaseGen/Method_4/src/vesselGen/save_stl_from_patches.py
        git rm     Aorta/ofCaseGen/Method_4/src/vesselGen/stlwrite.py
        git rm     Aorta/ofCaseGen/Method_4/src/vesselGen/vessel_spline.py
        git rm     Aorta/ofCaseGen/Method_4/src/vesselMorph/.DS_Store
        git rm     Aorta/ofCaseGen/Method_4/src/vesselMorph/compute_morphed_centerline.py
        git rm     Aorta/ofCaseGen/Method_4/src/vesselMorph/geometry_validator.py
        git rm     Aorta/ofCaseGen/Method_4/src/vesselMorph/morphing_validator.py
        git rm     Aorta/ofCaseGen/Method_4/src/vesselMorph/spherical_morphing.py
        git rm     Aorta/ofCaseGen/Method_4/src/vesselStats/.DS_Store
        git rm     Aorta/ofCaseGen/Method_4/src/vesselStats/parameter_sampler.py
        git rm     Aorta/ofCaseGen/Method_4/src/visualization/.DS_Store
        git rm     Aorta/ofCaseGen/Method_4/src/visualization/__init__.py
        git rm     Aorta/ofCaseGen/Method_4/src/visualization/visualization.py
